"""Static arXiv category taxonomy used to name identifiers stored in the corpus.

Mirrors https://arxiv.org/category_taxonomy. Identifiers are stable; names change rarely.
Archives retired before the modern scheme are included because old records still carry them.
"""

ARXIV_CATEGORIES: dict[str, tuple[str, str]] = {
    # group, name
    "cs.AI": ("Computer Science", "Artificial Intelligence"),
    "cs.AR": ("Computer Science", "Hardware Architecture"),
    "cs.CC": ("Computer Science", "Computational Complexity"),
    "cs.CE": ("Computer Science", "Computational Engineering, Finance, and Science"),
    "cs.CG": ("Computer Science", "Computational Geometry"),
    "cs.CL": ("Computer Science", "Computation and Language"),
    "cs.CR": ("Computer Science", "Cryptography and Security"),
    "cs.CV": ("Computer Science", "Computer Vision and Pattern Recognition"),
    "cs.CY": ("Computer Science", "Computers and Society"),
    "cs.DB": ("Computer Science", "Databases"),
    "cs.DC": ("Computer Science", "Distributed, Parallel, and Cluster Computing"),
    "cs.DL": ("Computer Science", "Digital Libraries"),
    "cs.DM": ("Computer Science", "Discrete Mathematics"),
    "cs.DS": ("Computer Science", "Data Structures and Algorithms"),
    "cs.ET": ("Computer Science", "Emerging Technologies"),
    "cs.FL": ("Computer Science", "Formal Languages and Automata Theory"),
    "cs.GL": ("Computer Science", "General Literature"),
    "cs.GR": ("Computer Science", "Graphics"),
    "cs.GT": ("Computer Science", "Computer Science and Game Theory"),
    "cs.HC": ("Computer Science", "Human-Computer Interaction"),
    "cs.IR": ("Computer Science", "Information Retrieval"),
    "cs.IT": ("Computer Science", "Information Theory"),
    "cs.LG": ("Computer Science", "Machine Learning"),
    "cs.LO": ("Computer Science", "Logic in Computer Science"),
    "cs.MA": ("Computer Science", "Multiagent Systems"),
    "cs.MM": ("Computer Science", "Multimedia"),
    "cs.MS": ("Computer Science", "Mathematical Software"),
    "cs.NA": ("Computer Science", "Numerical Analysis"),
    "cs.NE": ("Computer Science", "Neural and Evolutionary Computing"),
    "cs.NI": ("Computer Science", "Networking and Internet Architecture"),
    "cs.OH": ("Computer Science", "Other Computer Science"),
    "cs.OS": ("Computer Science", "Operating Systems"),
    "cs.PF": ("Computer Science", "Performance"),
    "cs.PL": ("Computer Science", "Programming Languages"),
    "cs.RO": ("Computer Science", "Robotics"),
    "cs.SC": ("Computer Science", "Symbolic Computation"),
    "cs.SD": ("Computer Science", "Sound"),
    "cs.SE": ("Computer Science", "Software Engineering"),
    "cs.SI": ("Computer Science", "Social and Information Networks"),
    "cs.SY": ("Computer Science", "Systems and Control"),

    "econ.EM": ("Economics", "Econometrics"),
    "econ.GN": ("Economics", "General Economics"),
    "econ.TH": ("Economics", "Theoretical Economics"),

    "eess.AS": ("Electrical Engineering and Systems Science", "Audio and Speech Processing"),
    "eess.IV": ("Electrical Engineering and Systems Science", "Image and Video Processing"),
    "eess.SP": ("Electrical Engineering and Systems Science", "Signal Processing"),
    "eess.SY": ("Electrical Engineering and Systems Science", "Systems and Control"),

    "math.AC": ("Mathematics", "Commutative Algebra"),
    "math.AG": ("Mathematics", "Algebraic Geometry"),
    "math.AP": ("Mathematics", "Analysis of PDEs"),
    "math.AT": ("Mathematics", "Algebraic Topology"),
    "math.CA": ("Mathematics", "Classical Analysis and ODEs"),
    "math.CO": ("Mathematics", "Combinatorics"),
    "math.CT": ("Mathematics", "Category Theory"),
    "math.CV": ("Mathematics", "Complex Variables"),
    "math.DG": ("Mathematics", "Differential Geometry"),
    "math.DS": ("Mathematics", "Dynamical Systems"),
    "math.FA": ("Mathematics", "Functional Analysis"),
    "math.GM": ("Mathematics", "General Mathematics"),
    "math.GN": ("Mathematics", "General Topology"),
    "math.GR": ("Mathematics", "Group Theory"),
    "math.GT": ("Mathematics", "Geometric Topology"),
    "math.HO": ("Mathematics", "History and Overview"),
    "math.IT": ("Mathematics", "Information Theory"),
    "math.KT": ("Mathematics", "K-Theory and Homology"),
    "math.LO": ("Mathematics", "Logic"),
    "math.MG": ("Mathematics", "Metric Geometry"),
    "math.MP": ("Mathematics", "Mathematical Physics"),
    "math.NA": ("Mathematics", "Numerical Analysis"),
    "math.NT": ("Mathematics", "Number Theory"),
    "math.OA": ("Mathematics", "Operator Algebras"),
    "math.OC": ("Mathematics", "Optimization and Control"),
    "math.PR": ("Mathematics", "Probability"),
    "math.QA": ("Mathematics", "Quantum Algebra"),
    "math.RA": ("Mathematics", "Rings and Algebras"),
    "math.RT": ("Mathematics", "Representation Theory"),
    "math.SG": ("Mathematics", "Symplectic Geometry"),
    "math.SP": ("Mathematics", "Spectral Theory"),
    "math.ST": ("Mathematics", "Statistics Theory"),

    "astro-ph": ("Physics", "Astrophysics"),
    "astro-ph.CO": ("Physics", "Cosmology and Nongalactic Astrophysics"),
    "astro-ph.EP": ("Physics", "Earth and Planetary Astrophysics"),
    "astro-ph.GA": ("Physics", "Astrophysics of Galaxies"),
    "astro-ph.HE": ("Physics", "High Energy Astrophysical Phenomena"),
    "astro-ph.IM": ("Physics", "Instrumentation and Methods for Astrophysics"),
    "astro-ph.SR": ("Physics", "Solar and Stellar Astrophysics"),
    "cond-mat": ("Physics", "Condensed Matter"),
    "cond-mat.dis-nn": ("Physics", "Disordered Systems and Neural Networks"),
    "cond-mat.mes-hall": ("Physics", "Mesoscale and Nanoscale Physics"),
    "cond-mat.mtrl-sci": ("Physics", "Materials Science"),
    "cond-mat.other": ("Physics", "Other Condensed Matter"),
    "cond-mat.quant-gas": ("Physics", "Quantum Gases"),
    "cond-mat.soft": ("Physics", "Soft Condensed Matter"),
    "cond-mat.stat-mech": ("Physics", "Statistical Mechanics"),
    "cond-mat.str-el": ("Physics", "Strongly Correlated Electrons"),
    "cond-mat.supr-con": ("Physics", "Superconductivity"),
    "gr-qc": ("Physics", "General Relativity and Quantum Cosmology"),
    "hep-ex": ("Physics", "High Energy Physics - Experiment"),
    "hep-lat": ("Physics", "High Energy Physics - Lattice"),
    "hep-ph": ("Physics", "High Energy Physics - Phenomenology"),
    "hep-th": ("Physics", "High Energy Physics - Theory"),
    "math-ph": ("Physics", "Mathematical Physics"),
    "nlin.AO": ("Physics", "Adaptation and Self-Organizing Systems"),
    "nlin.CD": ("Physics", "Chaotic Dynamics"),
    "nlin.CG": ("Physics", "Cellular Automata and Lattice Gases"),
    "nlin.PS": ("Physics", "Pattern Formation and Solitons"),
    "nlin.SI": ("Physics", "Exactly Solvable and Integrable Systems"),
    "nucl-ex": ("Physics", "Nuclear Experiment"),
    "nucl-th": ("Physics", "Nuclear Theory"),
    "physics.acc-ph": ("Physics", "Accelerator Physics"),
    "physics.ao-ph": ("Physics", "Atmospheric and Oceanic Physics"),
    "physics.app-ph": ("Physics", "Applied Physics"),
    "physics.atm-clus": ("Physics", "Atomic and Molecular Clusters"),
    "physics.atom-ph": ("Physics", "Atomic Physics"),
    "physics.bio-ph": ("Physics", "Biological Physics"),
    "physics.chem-ph": ("Physics", "Chemical Physics"),
    "physics.class-ph": ("Physics", "Classical Physics"),
    "physics.comp-ph": ("Physics", "Computational Physics"),
    "physics.data-an": ("Physics", "Data Analysis, Statistics and Probability"),
    "physics.ed-ph": ("Physics", "Physics Education"),
    "physics.flu-dyn": ("Physics", "Fluid Dynamics"),
    "physics.gen-ph": ("Physics", "General Physics"),
    "physics.geo-ph": ("Physics", "Geophysics"),
    "physics.hist-ph": ("Physics", "History and Philosophy of Physics"),
    "physics.ins-det": ("Physics", "Instrumentation and Detectors"),
    "physics.med-ph": ("Physics", "Medical Physics"),
    "physics.optics": ("Physics", "Optics"),
    "physics.plasm-ph": ("Physics", "Plasma Physics"),
    "physics.pop-ph": ("Physics", "Popular Physics"),
    "physics.soc-ph": ("Physics", "Physics and Society"),
    "physics.space-ph": ("Physics", "Space Physics"),
    "quant-ph": ("Physics", "Quantum Physics"),

    "q-bio": ("Quantitative Biology", "Quantitative Biology"),
    "q-bio.BM": ("Quantitative Biology", "Biomolecules"),
    "q-bio.CB": ("Quantitative Biology", "Cell Behavior"),
    "q-bio.GN": ("Quantitative Biology", "Genomics"),
    "q-bio.MN": ("Quantitative Biology", "Molecular Networks"),
    "q-bio.NC": ("Quantitative Biology", "Neurons and Cognition"),
    "q-bio.OT": ("Quantitative Biology", "Other Quantitative Biology"),
    "q-bio.PE": ("Quantitative Biology", "Populations and Evolution"),
    "q-bio.QM": ("Quantitative Biology", "Quantitative Methods"),
    "q-bio.SC": ("Quantitative Biology", "Subcellular Processes"),
    "q-bio.TO": ("Quantitative Biology", "Tissues and Organs"),

    "q-fin.CP": ("Quantitative Finance", "Computational Finance"),
    "q-fin.EC": ("Quantitative Finance", "Economics"),
    "q-fin.GN": ("Quantitative Finance", "General Finance"),
    "q-fin.MF": ("Quantitative Finance", "Mathematical Finance"),
    "q-fin.PM": ("Quantitative Finance", "Portfolio Management"),
    "q-fin.PR": ("Quantitative Finance", "Pricing of Securities"),
    "q-fin.RM": ("Quantitative Finance", "Risk Management"),
    "q-fin.ST": ("Quantitative Finance", "Statistical Finance"),
    "q-fin.TR": ("Quantitative Finance", "Trading and Market Microstructure"),

    "stat.AP": ("Statistics", "Applications"),
    "stat.CO": ("Statistics", "Computation"),
    "stat.ME": ("Statistics", "Methodology"),
    "stat.ML": ("Statistics", "Machine Learning"),
    "stat.OT": ("Statistics", "Other Statistics"),
    "stat.TH": ("Statistics", "Statistics Theory"),
}


def describe(category: str) -> tuple[str | None, str | None]:
    """Return the (group, name) pair for an arXiv category, or (None, None) when unrecognized."""
    entry = ARXIV_CATEGORIES.get(category)
    return entry if entry is not None else (None, None)
