#!/usr/bin/env bash
set -euo pipefail

: "${VANTA_MODULE_STAGE:?VANTA_MODULE_STAGE is required}"
: "${VANTA_MODULE_INSTALL_DIR:?VANTA_MODULE_INSTALL_DIR is required}"
: "${VANTA_MODULE_CURRENT_LINK:?VANTA_MODULE_CURRENT_LINK is required}"
: "${VANTA_MODULE_RUN_AS:?VANTA_MODULE_RUN_AS is required}"

for file in module.json server.py service.py browser.py download.py network_policy.py extraction.py artifact_protocol.py browser-retrieval.service; do
	test -f "$VANTA_MODULE_STAGE/$file"
done
for command in bash python3 chromium systemctl useradd runuser timeout; do
	command -v "$command" >/dev/null 2>&1
done
id "$VANTA_MODULE_RUN_AS" >/dev/null 2>&1

download_contact="${VANTA_MODULE_OPTION_DOWNLOAD_CONTACT:-}"
contact_pattern='^[A-Za-z0-9._%+@:/?#=&~-]{3,200}$'
if [ -n "$download_contact" ] && ! [[ "$download_contact" =~ $contact_pattern ]]; then
	echo "browser-retrieval: downloadContact contains unsupported characters" >&2
	exit 1
fi
dropin_dir=/etc/systemd/system/vantamcpd-browser-retrieval.service.d

service_user=vantamcpd-browser
if ! id "$service_user" >/dev/null 2>&1; then
	useradd --system --user-group --home-dir /nonexistent --shell /usr/sbin/nologin "$service_user"
fi
caller_uid=$(id -u "$VANTA_MODULE_RUN_AS")
caller_gid=$(id -g "$VANTA_MODULE_RUN_AS")
caller_group=$(id -gn "$VANTA_MODULE_RUN_AS")
usermod -a -G "$caller_group" "$service_user"

install -d -m 0755 /etc/vantamcpd "$dropin_dir"
env_tmp=$(mktemp /etc/vantamcpd/.browser-retrieval.XXXXXX)
dropin_tmp=$(mktemp "$dropin_dir/.artifacts.XXXXXX")
smoke_dir=$(mktemp -d /tmp/vantamcpd-browser-smoke.XXXXXX)
tmp="$VANTA_MODULE_INSTALL_DIR.tmp.$$"
trap 'rm -f "$env_tmp" "$dropin_tmp"; rm -rf "$smoke_dir" "$tmp"' EXIT
{
	printf 'VANTA_BROWSER_CALLER_UID=%s\nVANTA_BROWSER_CALLER_GID=%s\n' "$caller_uid" "$caller_gid"
	if [ -n "$download_contact" ]; then
		printf 'VANTA_BROWSER_DOWNLOAD_CONTACT=%s\n' "$download_contact"
	fi
	if [ -n "${VANTA_ARTIFACT_ROOT:-}" ]; then
		printf 'VANTA_ARTIFACT_ROOT=%s\n' "$VANTA_ARTIFACT_ROOT"
		printf 'VANTA_ARTIFACT_PROTOCOL_VERSION=%s\n' "${VANTA_ARTIFACT_PROTOCOL_VERSION:-1}"
	fi
} > "$env_tmp"
chmod 0600 "$env_tmp"
mv -f "$env_tmp" /etc/vantamcpd/browser-retrieval.env

if [ -n "${VANTA_ARTIFACT_ROOT:-}" ]; then
	# The leading '-' keeps browsing available when the artifact NFS mount is absent at service start.
	printf '# Generated by the VantaMCPd browser-retrieval installer.\n[Service]\nGroup=%s\nReadWritePaths=-%s\n' \
		"$caller_group" "$VANTA_ARTIFACT_ROOT" > "$dropin_tmp"
	chmod 0644 "$dropin_tmp"
	mv -f "$dropin_tmp" "$dropin_dir/artifacts.conf"
else
	rm -f "$dropin_dir/artifacts.conf"
fi

parent=$(dirname "$VANTA_MODULE_INSTALL_DIR")
mkdir -p "$parent"
rm -rf "$tmp"
mkdir -p "$tmp"
cp -a "$VANTA_MODULE_STAGE/." "$tmp/"
PYTHONDONTWRITEBYTECODE=1 python3 "$tmp/server.py" --self-test
PYTHONDONTWRITEBYTECODE=1 python3 "$tmp/browser.py"
PYTHONDONTWRITEBYTECODE=1 python3 "$tmp/artifact_protocol.py"
PYTHONDONTWRITEBYTECODE=1 VANTA_BROWSER_DOWNLOAD_CONTACT="$download_contact" python3 "$tmp/download.py"

chown -R "$service_user:$service_user" "$smoke_dir"
smoke_status=0
runuser -u "$service_user" -- env HOME="$smoke_dir" timeout 25s chromium \
	--headless=new --disable-gpu --disable-dev-shm-usage --no-first-run --no-default-browser-check \
	--user-data-dir="$smoke_dir/profile" --dump-dom 'data:text/html,<title>VantaBrowserSmoke</title><p>ready</p>' \
	> "$smoke_dir/output" 2> "$smoke_dir/error" || smoke_status=$?
if ! grep -q 'VantaBrowserSmoke' "$smoke_dir/output"; then
	# The EXIT trap deletes this directory, so echo Chromium's own error before it is lost.
	echo "browser-retrieval: Chromium smoke test failed (exit $smoke_status)." >&2
	echo "browser-retrieval: confirm the node permits unprivileged user namespaces." >&2
	tail -c 2000 "$smoke_dir/error" >&2
	exit 1
fi

rm -rf "$VANTA_MODULE_INSTALL_DIR"
mv "$tmp" "$VANTA_MODULE_INSTALL_DIR"
ln -sfn "$(basename "$VANTA_MODULE_INSTALL_DIR")" "$VANTA_MODULE_CURRENT_LINK"
trap - EXIT
rm -f "$dropin_tmp"
rm -rf "$smoke_dir"
