#!/usr/bin/env bash
set -euo pipefail

: "${VANTA_MODULE_STAGE:?VANTA_MODULE_STAGE is required}"
: "${VANTA_MODULE_INSTALL_DIR:?VANTA_MODULE_INSTALL_DIR is required}"
: "${VANTA_MODULE_CURRENT_LINK:?VANTA_MODULE_CURRENT_LINK is required}"
: "${VANTA_MODULE_RUN_AS:?VANTA_MODULE_RUN_AS is required}"

backend="${VANTA_MODULE_OPTION_BACKEND:-auto}"
service_user=vantamcpd-image
state_dir=/var/lib/vantamcpd-image
dropin_dir=/etc/systemd/system/vantamcpd-image-processing.service.d

clamp() {
	if [ "$1" -lt "$2" ]; then echo "$2"; elif [ "$1" -gt "$3" ]; then echo "$3"; else echo "$1"; fi
}

progress() {
	printf 'VANTA_PROGRESS {"phase":"%s","current":%s,"total":%s,"unit":"steps","message":"%s"}\n' "$1" "$2" "$3" "$4"
}

for file in module.json server.py service.py sandbox.py worker.py processing.py schemas.py artifact_io.py artifact_protocol.py policy.xml image-processing.service; do
	test -f "$VANTA_MODULE_STAGE/$file"
done
for command in bash python3 bwrap prlimit systemctl runuser useradd apt-get; do
	command -v "$command" >/dev/null 2>&1
done
id "$VANTA_MODULE_RUN_AS" >/dev/null 2>&1
case "$backend" in auto|imagemagick|pillow) ;; *) echo "invalid image backend: $backend" >&2; exit 1 ;; esac

export PYTHONDONTWRITEBYTECODE=1
export DEBIAN_FRONTEND=noninteractive
apt_flags=(-y -q --no-install-recommends -o Dpkg::Use-Pty=0 -o DPkg::Lock::Timeout=300 -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold)

progress packages 0 5 "Refreshing package indexes"
env DEBIAN_FRONTEND=noninteractive apt-get update -q -o Dpkg::Use-Pty=0 -o DPkg::Lock::Timeout=300 </dev/null
progress packages 1 5 "Installing the Pillow fallback and annotation font"
env DEBIAN_FRONTEND=noninteractive apt-get install "${apt_flags[@]}" python3-pil fonts-dejavu-core </dev/null
if [ "$backend" != pillow ]; then
	progress packages 2 5 "Installing ImageMagick"
	if ! env DEBIAN_FRONTEND=noninteractive apt-get install "${apt_flags[@]}" imagemagick </dev/null; then
		if [ "$backend" = imagemagick ]; then
			echo "the requested ImageMagick backend could not be installed" >&2
			exit 1
		fi
		echo "ImageMagick is unavailable; auto mode will use python3-pil" >&2
	fi
else
	progress packages 2 5 "Using the Pillow-only backend"
fi

progress environment 3 5 "Preparing the service account and resource limits"
if ! id "$service_user" >/dev/null 2>&1; then
	useradd --system --user-group --home-dir /nonexistent --shell /usr/sbin/nologin "$service_user"
fi
caller_uid=$(id -u "$VANTA_MODULE_RUN_AS")
caller_gid=$(id -g "$VANTA_MODULE_RUN_AS")
caller_group=$(id -gn "$VANTA_MODULE_RUN_AS")
usermod -a -G "$caller_group" "$service_user"

mem_total_mb=$(awk '/^MemTotal:/ {printf "%d", $2 / 1024}' /proc/meminfo)
cores=$(nproc)
cgroup_high_mb=$(clamp $((mem_total_mb * 60 / 100)) 384 8192)
cgroup_max_mb=$(clamp $((mem_total_mb * 75 / 100)) 448 8192)
if [ "$cores" -ge 4 ] && [ "$mem_total_mb" -ge 2048 ]; then derived_concurrency=2; else derived_concurrency=1; fi
concurrent_calls=$(clamp "${VANTA_MODULE_OPTION_CONCURRENT_CALLS:-$derived_concurrency}" 1 4)
memory_mb=$(clamp "${VANTA_MODULE_OPTION_MAX_MEMORY_MB:-$((cgroup_high_mb / concurrent_calls))}" 192 2048)
timeout_ms=$(clamp "${VANTA_MODULE_OPTION_MAX_TIMEOUT_MS:-60000}" 5000 120000)
calls_per_minute=$(clamp "${VANTA_MODULE_OPTION_CALLS_PER_MINUTE:-$((12 * concurrent_calls))}" 1 120)
cpu_quota=$((cores * 100))
if [ "$cpu_quota" -gt 200 ]; then cpu_quota=200; fi
tasks_max=$((48 * concurrent_calls + 24))

install -d -m 0755 /etc/vantamcpd "$dropin_dir"
env_tmp=$(mktemp /etc/vantamcpd/.image-processing.XXXXXX)
dropin_tmp=$(mktemp "$dropin_dir/.limits.XXXXXX")
tmp="$VANTA_MODULE_INSTALL_DIR.tmp.$$"
trap 'rm -f "$env_tmp" "$dropin_tmp"; rm -rf "$tmp"' EXIT

{
	printf 'VANTA_IMAGE_CALLER_UID=%s\n' "$caller_uid"
	printf 'VANTA_IMAGE_CLIENT_GID=%s\n' "$caller_gid"
	printf 'VANTA_IMAGE_BACKEND=%s\n' "$backend"
	printf 'VANTA_IMAGE_MEMORY_MB=%s\n' "$memory_mb"
	printf 'VANTA_IMAGE_TIMEOUT_MS=%s\n' "$timeout_ms"
	printf 'VANTA_IMAGE_CONCURRENT_CALLS=%s\n' "$concurrent_calls"
	printf 'VANTA_IMAGE_CALLS_PER_MINUTE=%s\n' "$calls_per_minute"
	if [ -n "${VANTA_ARTIFACT_ROOT:-}" ]; then
		printf 'VANTA_ARTIFACT_ROOT=%s\n' "$VANTA_ARTIFACT_ROOT"
		printf 'VANTA_ARTIFACT_PROTOCOL_VERSION=%s\n' "${VANTA_ARTIFACT_PROTOCOL_VERSION:-1}"
	fi
} > "$env_tmp"
chmod 0644 "$env_tmp"
mv -f "$env_tmp" /etc/vantamcpd/image-processing.env

{
	printf '# Generated by the VantaMCPd image-processing installer from this node.\n[Service]\n'
	printf 'MemoryHigh=%sM\nMemoryMax=%sM\nCPUQuota=%s%%\nTasksMax=%s\n' "$cgroup_high_mb" "$cgroup_max_mb" "$cpu_quota" "$tasks_max"
	if [ -n "${VANTA_ARTIFACT_ROOT:-}" ]; then
		printf 'Group=%s\nReadWritePaths=%s\n' "$caller_group" "$VANTA_ARTIFACT_ROOT"
	fi
} > "$dropin_tmp"
chmod 0644 "$dropin_tmp"
mv -f "$dropin_tmp" "$dropin_dir/limits.conf"
install -d -m 0700 -o "$service_user" -g "$service_user" "$state_dir" "$state_dir/calls"

parent=$(dirname "$VANTA_MODULE_INSTALL_DIR")
mkdir -p "$parent"
rm -rf "$tmp"
mkdir -p "$tmp"
cp -a "$VANTA_MODULE_STAGE/." "$tmp/"
chmod -R a+rX "$tmp"

progress verify 4 5 "Checking schemas, engines, policy, and sandbox"
python3 "$tmp/schemas.py"
python3 "$tmp/artifact_io.py"
python3 "$tmp/processing.py"
python3 "$tmp/worker.py" --self-test
python3 "$tmp/sandbox.py"
python3 "$tmp/service.py" --self-test
python3 "$tmp/server.py" --self-test
runuser -u "$service_user" -- env PYTHONDONTWRITEBYTECODE=1 VANTA_IMAGE_INSTALL_DIR="$tmp" VANTA_IMAGE_STATE_DIR="$state_dir" \
	VANTA_IMAGE_BACKEND="$backend" VANTA_IMAGE_MEMORY_MB="$memory_mb" python3 "$tmp/sandbox.py" --smoke-test

rm -rf "$VANTA_MODULE_INSTALL_DIR"
mv "$tmp" "$VANTA_MODULE_INSTALL_DIR"
ln -sfn "$(basename "$VANTA_MODULE_INSTALL_DIR")" "$VANTA_MODULE_CURRENT_LINK"
trap - EXIT
rm -f "$env_tmp" "$dropin_tmp" 2>/dev/null || true
progress complete 5 5 "Image Processing is ready"